# Docker compose file used for development.

version: "3"

services:
  roulette_api:
    container_name: roulette
    build: .
    restart: unless-stopped
    command: npm run dev
    environment:
      NODE_ENV: "development"
      PORT: 3000
      REDIS_PORT: 6379
      REDIS_PASSWORD: password
      REDIS_DB: 0
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - redis

  redis:
    container_name: redis
    image: redis:5.0.9-alpine3.11
    restart: unless-stopped
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
